name: Test Battery State Publisher

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.2
        with:
          use-ros2-testing: true
          required-ros-distributions: humble  # 'version'ではなく、この記述を使用

      - name: Install dependencies
        run: |
          # GPGキーを追加
          curl -sSL http://packages.ros.org/ros2/ubuntu/ros.key | sudo tee /usr/share/keyrings/ros-archive-keyring.gpg > /dev/null

          # ROS2のリポジトリを追加
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list

          # パッケージリストを更新
          sudo apt-get update

          # 依存関係のインストール
          sudo apt-get install -y python3-colcon-common-extensions
          pip install pytest

      - name: Run tests
        run: |
         colcon test --packages-select mypkg --event-handlers console_direct+
