name: ROS2 Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest  # 使用するROS2コンテナ

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # リポジトリをクローン

    - name: Setup ROS2
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions
        sudo apt install -y acpi  # acpiコマンドをインストール

    - name: Install ROS2 dependencies
      run: |
        sudo apt install -y ros-humble-desktop

    - name: Build the ROS2 workspace
      run: |
        rsync -av ./ /root/ros2_ws/src/mypkg/
        cd /root/ros2_ws
        colcon build --symlink-install

    - name: Source ROS2 workspace
      run: |
        bash -c "source /root/ros2_ws/install/setup.bash"  # bashでsourceを実行

    - name: Run the battery state publisher
      run: |
        bash -c "source /root/ros2_ws/install/setup.bash && ros2 run mypkg battery_state_publisher"  # bashで実行

    - name: Test battery state and level
      run: |
        bash -c "source /root/ros2_ws/install/setup.bash && ros2 topic echo /battery_state"
        bash -c "source /root/ros2_ws/install/setup.bash && ros2 topic echo /battery_level"

