name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.3
        with:
          distribution: humble
          install-source-packages: true

      - name: Install ROS 2 dependencies
        run: |
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build the workspace
        run: |
          colcon build
          colcon test
          colcon test-result --verbose

