name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # ROS2 Humbleに対応したUbuntuバージョン
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS2
        run: |
          sudo apt update && sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep
          sudo rosdep init
          rosdep update
          echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV
        shell: bash  # シェルを明示的に指定

      - name: Setup workspace
        run: |
          sudo apt install -y python3-pip
          pip3 install -r requirements.txt
          source /opt/ros/humble/setup.bash
          colcon build

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test

