name: Test Battery State Publisher

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: humble  # ROS2のバージョンを指定

      - name: Add ROS2 GPG key and repository
        run: |
          sudo curl -sSL http://packages.ros.org/ros2/ubuntu/ros.key | sudo apt-key add -
          echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions
          pip install pytest

      - name: Run tests
        run: |
          colcon test --packages-select mypkg

