name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup ROS 2 Humble
        run: |
          echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
          source /opt/ros/humble/setup.bash

      - name: Prepare workspace
        run: |
          mkdir -p ~/ros2_ws/src
          rsync -av ./ ~/ros2_ws/src/mypkg/

      - name: Install ROS 2 dependencies
        run: |
          cd ~/ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build and test
        run: |
          set -e
          cd ~/ros2_ws
          colcon build
          source install/setup.bash
          bash ./src/mypkg/test/test.bash

