name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # acpi をインストール
    - name: Install acpi
      run: sudo apt-get update && sudo apt-get install -y acpi

    # ROS2 ワークスペースをビルド
    - name: Build ROS2 workspace
      run: |
        cd ~/ros2_ws
        colcon build

    # ROS2 環境を設定
    - name: Source ROS2 setup
      run: |
        source ~/ros2_ws/install/setup.bash
        source ~/.bashrc

    # スクリプトを実行
    - name: Run the test script
      run: |
        bash ~/ros2_ws/src/mypkg/test/test.bash

